### ISSUE TITLE
where do we specify NodeSelectors and taints and tolerations in infuxdb kind object?

### ISSUE THREAD

**Issue by tprakash17** [influxdata/influxdata-operator#10]
where do we specify NodeSelectors and taints and tolerations in infuxdb kind object?
I tried few combination of specifying node selector and PodAffinity for influxdb kind object, but none of them work. 

Can you please add sample here?

**Comment by AdheipSingh** [comment]
Currently if you see the spec their isn't any, ill add PR for it. :)

**Comment by tprakash17** [comment]
Also, define environment variables for influxdb statefulset in this influxdb `kind` crd.
```
---
apiVersion: influxdata.com/v1alpha1
kind: Influxdb
metadata:
  name: influxdb
  namespace: influxdb
spec:
  nodeSelector:
    app: sensugo
  tolerations:
    - effect: NoExecute
      key: app
      operator: Equal 
      value: sensugo     
  size: 1
  baseImage: influxdb:1.7.1 #defautl  influxdb:1.6.3-alpine
  imagePullPolicy: Always
  pod:
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 0.2
        memory: 256Mi
    env:
      name: INFLUXDB_HTTP_AUTH_ENABLED
      value: true
      name: INFLUXDB_ADMIN_USER
      value: admin
      name: INFLUXDB_ADMIN_PASSWORD
      value: testpassword
      name: INFLUXDB_WRITE_USER
      value: testuser
      name: INFLUXDB_WRITE_USER_PASSWORD
      value: testpassword
      name: INFLUXDB_GRAPHITE_ENABLED
      value: true
      name: INFLUXDB_ADMIN_ENABLED
      value: true
      name: INFLUXDB_DB
      value: testdb
    persistentVolumeClaim:
      metadata:
        name: "influxdb-data-pvc"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: performance-retain
        resources:
          requests:
            storage: 5Gi
```
Above doesn't work but it doesn't throw error as well. Once these variables start reflecting i can change them to use `secrets`.
