### ISSUE TITLE
Create Local Storage Failed(spec.nodeAffinity: Required value: Local volume requires node affinity)

### ISSUE THREAD

**Issue by zealzhangz** [influxdata/influxdata-operator#15]
Create PV failed

```bash
kubectl create -f local_storage.yaml
storageclass.storage.k8s.io/standard-resize created
The PersistentVolume "influxdb-data-pv" is invalid: spec.nodeAffinity: Required value: Local volume requires node affinity
```
I found sample example,It can create success, but it's uncertain whether it really provides the ability to store data.
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-resize
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-data-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  local:
    path: /var/lib/influxdb/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - my-node
```
